refactorig: client.py and login_form.py
nm17/netschoolapi pull request #11
Opened 2020-09-22 23:07 UTC by homus32

changed examples

2020-09-23 05:55 UTC, igorlanov requested changes
1. Удалить комментарии. Во-первых, они очевидны, во-вторых, они содержат мат, что не круто, в-третьих, они содержат ошибки.
2. `async with self.session as s` лучше заменит на `async with self.session as session` для удобочитаемости

— netschoolapi/client.py — 

3. в методе logout можно безболезненно убрать async with
4. :195 — `for a ...` заменить на `for announcement ...`
5. NetSchoolAPI — поля класса лучше вернуть обратно из инита
6. :get_prepare_data что значат все эти k, v, i? Лучше дать подходящие имена
7. :140–142 — аргументы функции уместятся в одну строку

2020-09-23 10:21 UTC, nm17 requested changes

2020-09-23 10:21 UTC, nm17 commented on requirements.txt
> +trio
trio давно убрал уже, из `examples/` его тоже убери.

2020-09-23 10:21 UTC, nm17 commented on requirements.txt
> +setuptools
Что тут setuptools делает?

2020-09-23 10:21 UTC, nm17 commented on netschoolapi/client.py
> -            ).hexdigest()
Отформатируй black-ом.

2020-09-23 10:21 UTC, nm17 commented on netschoolapi/client.py
> +        *,
Это я точно не приму, всем кто использовал порядковые аргументы в функции login это сломает код. И вообще верни все параметры функции как они были до этого.

2020-09-23 10:21 UTC, nm17 commented on examples/login_form.py
> +import trio
Смотри мой коммент про трио в requirements.txt

2020-09-23 10:49 UTC, homus32 commented on requirements.txt
> +trio
ок

2020-09-23 10:49 UTC, homus32 commented on requirements.txt
> +setuptools
ок

2020-09-23 10:50 UTC, homus32 commented on netschoolapi/client.py
> -            ).hexdigest()
ок

2020-09-23 10:50 UTC, homus32 commented on netschoolapi/client.py
> +        *,
ок

2020-09-23 10:50 UTC, homus32 commented on examples/login_form.py
> +import trio
ок

2020-09-23 23:50 UTC, homus32 commented
Ну примите

2020-09-24 10:34 UTC, nm17 approved these changes
Пока наверное сойдёт, потом сделаю тесты для loginform-а и если что-то совсем будет плохо ревертну всё обратно.

2020-09-24 10:34 UTC, merged

2020-09-24 20:52 UTC, homus32 commented
> Пока наверное сойдёт, потом сделаю тесты для loginform-а и если что-то совсем будет плохо ревертну всё обратно.

Совсем плохо не будет