Получение данных через context в методе `.login()`
nm17/netschoolapi pull request #35
Opened 2021-05-09 06:40 UTC by tulen34

2021-05-09 06:47 UTC, nm17 requested changes

2021-05-09 06:47 UTC, nm17 commented on netschoolapi/netschoolapi.py
> +        context = responce.json()
Тут должно быть `response`, а не `responce`.

2021-05-09 06:47 UTC, nm17 commented on netschoolapi/netschoolapi.py
> +        responce = await self._client.get('context')
Немного не понимаю откуда взялся этот `/webapi/context`, расскажи по подробнее как он работает и есть ли он везде.

2021-05-09 06:51 UTC, nm17 commented on netschoolapi/netschoolapi.py
> +        responce = await self._client.get('context')
Только что проверил на моём sgo.cit73.ru, GET на `/webapi/context` выдаёт `Ошибка доступа`

2021-05-09 14:56 UTC, tulen34 commented on netschoolapi/netschoolapi.py
> +        responce = await self._client.get('context')
Я так понял, что `/webapi/context` выдаёт информацию о текущей сессии после авторизации. Не знаю есть ли он везде, но на sgo.volganet.ru работает после отправления запроса на `/webapi/login` и выдаёт такой вывод:
```json
{
    "at":"10461637561789739479710175",
    "userId":461706,
    "funcType":"School",
    "schoolId":1250,
    "schoolYearId":82742,
    "globalYearId":20,
    "emId":null,
    "productName":"Сетевой Город. Образование",
    "userLanguage":"",
    "version":"4.75.55320",
    "versionDate":null,
    "organizationName":"МОУ СШ № 28",
    "menuContext":{
        
    },
    "rights":[
        "arCalendarViewSelf",
        "arReportsViewForAssignedClass",
        "arAnnouncementView",
        "arMessagesSendReceive",
        "arAssignmentsViewComplete",
        "arLAViewMaterials",
        "arForumSendReceive"
    ],
    "roles":[
        "Student"
    ],
    "schoolyear":{
        "globalYear":{
            "startDate":"2020-09-01T00:00:00",
            "endDate":"2021-08-31T00:00:00",
            "id":20,
            "name":"2020/2021"
        },
        "schoolId":1250,
        "startDate":"2020-09-01T00:00:00",
        "endDate":"2021-08-31T00:00:00",
        "closed":"Open",
        "id":82742,
        "name":"2020/2021"
    },
    "user":{
        "id":461706,
        "name":"Глушонков Илья"
    },
    "organization":{
        "id":1250,
        "name":"МОУ СШ № 28"
    },
    "dateFormat":"dd\u0001mm\u0001yyyy\u0001.",
    "timeFormat":"hh\u0001mm\u0001:\u0001\u0001"
}
```

2021-05-10 07:12 UTC, igorlanov commented on netschoolapi/netschoolapi.py
> +        responce = await self._client.get('context')
В ранних версиях мы получали всё через контекст. Но у этого решения две проблемы:

1. Если к аккаунту привязано больше одного ученика, то всё поломается

2. Если пользователь — родитель, то дневник получить не получится: будет пустой список

Из-за этих двух причин некоторые (включая меня) не могли получить дневник.

А на самом деле, это решение хорошее, если бы не проблемы, которые я описал выше

2021-05-10 07:17 UTC, igorlanov commented on netschoolapi/netschoolapi.py
> +        responce = await self._client.get('context')
Отвечаю, почему @nm17 получает `Ошибку доступа`. Как я понял, ты просто вбил это в адресную строку. Да, так не получится получить контекст, т.к. чтобы его получить, нужно войти в СГО, точнее в хедерах должен быть `at`. Проще говоря, через клиент это получится сделать. Более того, если даже залогиниться на сайте и перейти на `/webapi/context`, то всё опять поломается, потому, что хедеры сессии слетают.

2021-05-10 07:20 UTC, closed without merging