Removed type[] Python 3.9 thingys4da better compatibility
nm17/netschoolapi pull request #38
Opened 2021-08-31 15:57 UTC by megahomyak

2021-09-13 13:45 UTC, nm17 requested changes

2021-09-13 13:45 UTC, nm17 commented on netschoolapi/netschoolapi.py
> +    async def download_attachment(
Не хватает метода где можно получить имя файла и его байты в виде `Tuple[str, bytes]`. Было бы очень полезно.

2021-09-13 13:57 UTC, megahomyak commented on netschoolapi/netschoolapi.py
> +    async def download_attachment(
А как назвать такой метод?

2021-09-13 14:15 UTC, lentryd commented on netschoolapi/netschoolapi.py
> +    async def download_attachment(
Например fileName() и fileByte()

2021-09-14 21:12 UTC, megahomyak commented on netschoolapi/netschoolapi.py
> +    async def download_attachment(
добавил download_attachment_as_bytes. Название аттача не возвращает, т.к. оно уже лежит в attachment.name

2021-09-14 21:13 UTC, merged